<AppIcon@BoxLayout>:
    orientation: "vertical"
    spacing: 2
    canvas.before:
        Color:
            rgba:(1,1,1,0)
        Rectangle:
            size: self.size
            pos: self.pos
    Button:
        id:image
        text: "icon image"
        size_hint_y:0.8

    Label:
        id:name
        text:"icon_name"
        size_hint_y:0.2

<dock>:
    canvas.before:
        Color:
            rgba:(1,0.5,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    GridLayout:
        cols:20
        AppIcon:
        AppIcon: