# Pre-commit hooks.
# python3 -m pip install pre-commit
# pre-commit install

repos:

  # Format Python
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  # Sort imports
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
        additional_dependencies: ["toml"]

  # Lint Python
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
